"""
Export manager: JSON and PDF/Markdown report generation.
"""
import json
from datetime import datetime


def to_json(results: dict) -> str:
    """Serialize full pipeline results to JSON string."""
    return json.dumps(results, indent=2, ensure_ascii=False)


def to_markdown_report(results: dict, context: dict) -> str:
    """Generate a clean Markdown report from pipeline results."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    papers = results.get("papers", [])
    gaps = results.get("gaps", [])
    proposals = results.get("proposals", [])
    communities = results.get("communities", [])

    lines = []
    lines.append(f"# Research Gap Analysis Report")
    lines.append(f"*Generated: {now}*\n")

    lines.append(f"## Research Context")
    lines.append(f"- **Domain:** {context.get('domain', 'N/A')}")
    lines.append(f"- **Interest:** {context.get('interest', 'N/A')}")
    lines.append(f"- **Gap Type:** {context.get('gap_type', 'N/A')}\n")

    lines.append(f"## Papers Analyzed ({len(papers)})")
    for i, p in enumerate(papers, 1):
        wiki = p.get("wiki", {})
        lines.append(f"\n### {i}. {wiki.get('title', p.get('filename', f'Paper {i}'))}")
        contribs = wiki.get("contributions", [])
        if contribs:
            lines.append("**Key Contributions:**")
            for c in contribs[:3]:
                lines.append(f"- {c}")
        limitations = wiki.get("limitations", [])
        if limitations:
            lines.append("**Stated Limitations:**")
            for lim in limitations[:3]:
                lines.append(f"- {lim}")

    if communities:
        lines.append(f"\n## Knowledge Communities ({len(communities)})")
        for i, c in enumerate(communities, 1):
            lines.append(f"\n### Community {i}: {c.get('theme', 'N/A')}")
            lines.append(c.get("summary", ""))

    lines.append(f"\n## Identified Research Gaps ({len(gaps)})")
    for i, g in enumerate(gaps, 1):
        status = g.get("validation_status", "unknown")
        status_emoji = {"open": "🟢", "partial": "🟡", "solved": "🔴"}.get(status, "⚪")
        lines.append(f"\n### Gap {i}: {g.get('title', 'Untitled')} {status_emoji}")
        lines.append(f"**Type:** {g.get('gap_type', 'N/A')} | **Confidence:** {g.get('confidence', 'N/A')} | **Status:** {status}")
        lines.append(f"\n{g.get('description', '')}")
        evidence = g.get("evidence", [])
        if evidence:
            lines.append("\n**Evidence:**")
            for e in evidence:
                lines.append(f"- {e}")
        existing = g.get("existing_papers", [])
        if existing:
            lines.append("\n**Related Existing Work:**")
            for ep in existing[:2]:
                lines.append(f"- {ep.get('title', 'N/A')} ({ep.get('year', 'N/A')})")

    lines.append(f"\n## Research Proposals ({len(proposals)})")
    for i, p in enumerate(proposals, 1):
        lines.append(f"\n### Proposal {i}: {p.get('title', 'Untitled')}")
        lines.append(f"**Confidence:** {p.get('confidence', 'N/A')}")
        lines.append(f"\n**Problem Statement:** {p.get('problem_statement', '')}")
        lines.append(f"\n**Proposed Methodology:** {p.get('methodology', '')}")
        lines.append(f"\n**Novelty:** {p.get('novelty', '')}")
        builds_on = p.get("builds_on", [])
        if builds_on:
            lines.append(f"\n**Builds On:** {', '.join(builds_on)}")

    lines.append(f"\n---\n*Report generated by Research Gap Analyzer*")
    return "\n".join(lines)
